name: Deploy Prod
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false
jobs:
  deploy-prod:
    name: Deploy Packages to Prod
    runs-on: ubuntu-latest
    needs: deploy-test
    environment: prod
    env:
      NETLIFY_AUTH_TOKEN: ${{secrets.NETLIFY_AUTH_TOKEN}}
      NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: Build
        run: yarn lerna run build --since HEAD~1
      - name: Deploy
        run: yarn lerna run deploy --since HEAD~1

